import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import type { NextRequest } from 'next/server';
import { SESSION_COOKIE } from '@/server/auth';

/**
 * DEV ONLY — sets the session cookie directly from a URL parameter.
 * Disabled in production (returns 404).
 *
 * Usage: /dev-set-session?id=<sessionId>
 * Generated by scripts/dev-login.ts
 */
export async function GET(req: NextRequest): Promise<Response> {
  if (process.env.NODE_ENV === 'production') {
    return new Response('Not found', { status: 404 });
  }

  const id = req.nextUrl.searchParams.get('id');
  if (!id) return new Response('Missing id', { status: 400 });

  const jar = await cookies();
  jar.set(SESSION_COOKIE, id, {
    httpOnly: true,
    sameSite: 'lax',
    secure: false,
    path: '/',
    maxAge: 60 * 60 * 24 * 30,
  });

  redirect('/');
}
